# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Ftable_config = debug

else ifeq ($(config),release)
  Ftable_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Ftable

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Ftable:
ifneq (,$(Ftable_config))
	@echo "==== Building Ftable ($(Ftable_config)) ===="
	@${MAKE} --no-print-directory -C . -f Ftable.make config=$(Ftable_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Ftable.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Ftable"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"